### ISSUE TITLE
download-best-solutions fails with current API

### ISSUE THREAD

**Issue by gollux** [ReCodEx/cli-old#4]
"recodex assignments download-best-solution" fails with the current version of ReCodEx at MFF. When it tries to print the message "Downloading best solutions [...]", it looks up `assginment["name"]`, which is no longer there. Instead, it is inside `assignment["localizedTexts"]`.

**Comment by SemaiCZE** [comment]
Thanks for reporting, should be fixed now.

**Comment by gollux** [comment]
Thanks!
